on:
  workflow_call:
    inputs:
      image_repository:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: 'Dockerfile'
      checkout_repository:
        required: false
        type: string
        default: 'axieinfinity/ronin'
      checkout_ref:
        required: false
        type: string
        default: 'master'
      checkout_path:
        required: false
        type: string
        default: 'ronin'
      build_context:
        required: false
        type: string
        default: '.'
      docker_push:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: [self-hosted, dockerize]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout Repo'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8' #v3.1.0

      - name: 'Checkout Lib Repo'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8' #v3.1.0
        with:
          repository: ${{ inputs.checkout_repository }}
          ref: ${{ inputs.checkout_ref }}
          path: ${{ inputs.checkout_path }}

      - id: 'meta'
        name: 'Docker Meta'
        uses: 'docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea' #v4.1.1
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
        with:
          images: ${{ inputs.image_repository }}
          tags: |
            type=ref,suffix=-{{sha}},event=branch
            type=ref,suffix=-{{sha}},event=pr
            type=ref,suffix=-{{sha}},event=tag
            type=semver,event=tag,pattern={{raw}}

      # Enable Registry Cache
      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325' #v2.2.1

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        if: ${{ inputs.docker_push }}
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d' #v0.8.3
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GH_ACTIONS_WIP }}
          service_account: ${{ secrets.GH_ACTIONS_SA_GCR }}

      - name: 'Login to GAR'
        uses: 'docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a' #v2.1.0
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: 'Build and Push'
        uses: 'docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5' #v3.2.0
        with:
          context: ${{ inputs.build_context }}
          file: ${{ inputs.dockerfile_path }}
          push: ${{ inputs.docker_push }}
          tags: ${{ steps.meta.outputs.tags }}
          secrets: |
            "github_token=${{ steps.gh-app.outputs.token }}"
