on:
  workflow_call:
    inputs:
      node_version:
        description: 'The Node version to download (if necessary) and use.'
        required: false
        type: string
        default: 'latest'
      registry_url:
        description: 'Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.'
        required: false
        type: string
      scope:
        description: 'Optional scope for authenticating against scoped registries.'
        required: false
        type: string

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2

      - name: 'Setup Node'
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #v3.4.1
        with:
          node-version: '${{ inputs.node_version }}'
          registry-url: '${{ inputs.registry_url }}'
          scope: '${{ inputs.scope }}'

      - name: 'Install dependencies'
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: 'Check eslint'
        run: yarn lint

      - name: 'Build Packages'
        run: yarn build

      - name: 'Run unittest'
        run: yarn test
