on:
  workflow_call:
    inputs:
      node_version:
        description: "The Node version to download (if necessary) and use."
        required: false
        type: string
        default: "latest"
      registry_url:
        description: "Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN."
        required: false
        type: string
      scope:
        description: "Optional scope for authenticating against scoped registries."
        required: false
        type: string
      working_directory:
        description: "The working directory of where to run the command."
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.0.2

      - name: "Setup Node"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #v3.4.1
        with:
          node-version: "${{ inputs.node_version }}"
          registry-url: "${{ inputs.registry_url }}"
          scope: "${{ inputs.scope }}"

      - name: "Install dependencies"
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: "Publish packages"
        run: pnpm publish
        working-directory: "${{ inputs.working_directory }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
