on:
  workflow_call:
    inputs:
      pnpm_version:
        description: "Optional pnpm version"
        required: false
        type: string
        default: "7.12.2"

      bun_version:
        description: "Optional bun version"
        required: false
        type: string
        default: "latest"

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.0.2

      - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd #2.2.4
        with:
          version: ${{ inputs.pnpm_version }}

      - uses: xhyrom/setup-bun@0ec953ee6d7a21c8bcefd4afe696a83930d8bb63 #0.1.7
        with:
          bun-version: ${{ inputs.bun_version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install dependencies"
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: "Check eslint"
        run: pnpm run lint

      - name: "Build Packages"
        run: pnpm run build

      - name: "Run unittest"
        run: pnpm run test
