name: "Check PR"

on: push
jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - name: Base
        uses: axieinfinity/workflows-samples/.github/workflows/platform-npm-base.yml
        with:
          registry_url: 'https://npm.pkg.github.com'
          scope: '@axieinfinity'

      - name: "Check eslint"
        run: pnpm run lint

      - name: "Build Packages"
        run: pnpm run build

      - name: "Run unittest"
        run: pnpm run test
