on:
  workflow_call:
    inputs:
      node_version:
        description: 'The Node version to download (if necessary) and use.'
        required: false
        type: string
        default: 'latest'
      node_options:
        description: 'node options'
        required: false
        type: string
      node_script:
        description: 'Script to execute'
        required: false
        type: string
      node_arguments:
        description: 'node arguments'
        required: false
        type: string

jobs:
  nodejs:
    runs-on: [self-hosted, gke]
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3.0.2

      - name: 'Setup Node'
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c #v3.4.1
        with:
          node-version: '${{ inputs.node_version }}'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Run with Node'
        run: node ${{ inputs.node_options }} ${{ inputs.node_script }} ${{ inputs.node_arguments }}
